// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_file_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_file_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_file_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_file_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_file_2eproto;
namespace proto {
class FileMeta;
struct FileMetaDefaultTypeInternal;
extern FileMetaDefaultTypeInternal _FileMeta_default_instance_;
class FileMetaResume;
struct FileMetaResumeDefaultTypeInternal;
extern FileMetaResumeDefaultTypeInternal _FileMetaResume_default_instance_;
class FileTrunk;
struct FileTrunkDefaultTypeInternal;
extern FileTrunkDefaultTypeInternal _FileTrunk_default_instance_;
}  // namespace proto
PROTOBUF_NAMESPACE_OPEN
template<> ::proto::FileMeta* Arena::CreateMaybeMessage<::proto::FileMeta>(Arena*);
template<> ::proto::FileMetaResume* Arena::CreateMaybeMessage<::proto::FileMetaResume>(Arena*);
template<> ::proto::FileTrunk* Arena::CreateMaybeMessage<::proto::FileTrunk>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace proto {

// ===================================================================

class FileMeta final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:proto.FileMeta) */ {
 public:
  inline FileMeta() : FileMeta(nullptr) {}
  ~FileMeta() override;
  explicit PROTOBUF_CONSTEXPR FileMeta(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FileMeta(const FileMeta& from);
  FileMeta(FileMeta&& from) noexcept
    : FileMeta() {
    *this = ::std::move(from);
  }

  inline FileMeta& operator=(const FileMeta& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileMeta& operator=(FileMeta&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileMeta& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileMeta* internal_default_instance() {
    return reinterpret_cast<const FileMeta*>(
               &_FileMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FileMeta& a, FileMeta& b) {
    a.Swap(&b);
  }
  inline void Swap(FileMeta* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileMeta* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileMeta* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FileMeta>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FileMeta& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FileMeta& from) {
    FileMeta::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileMeta* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "proto.FileMeta";
  }
  protected:
  explicit FileMeta(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUsrPathFieldNumber = 4,
    kLocalPathFieldNumber = 5,
    kHashFieldNumber = 6,
    kIdFieldNumber = 1,
    kSizeFieldNumber = 2,
    kBeginIdxFieldNumber = 3,
  };
  // string usr_path = 4;
  void clear_usr_path();
  const std::string& usr_path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_usr_path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_usr_path();
  PROTOBUF_NODISCARD std::string* release_usr_path();
  void set_allocated_usr_path(std::string* usr_path);
  private:
  const std::string& _internal_usr_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_usr_path(const std::string& value);
  std::string* _internal_mutable_usr_path();
  public:

  // string local_path = 5;
  void clear_local_path();
  const std::string& local_path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_local_path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_local_path();
  PROTOBUF_NODISCARD std::string* release_local_path();
  void set_allocated_local_path(std::string* local_path);
  private:
  const std::string& _internal_local_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_local_path(const std::string& value);
  std::string* _internal_mutable_local_path();
  public:

  // string hash = 6;
  void clear_hash();
  const std::string& hash() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_hash(ArgT0&& arg0, ArgT... args);
  std::string* mutable_hash();
  PROTOBUF_NODISCARD std::string* release_hash();
  void set_allocated_hash(std::string* hash);
  private:
  const std::string& _internal_hash() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_hash(const std::string& value);
  std::string* _internal_mutable_hash();
  public:

  // uint64 id = 1;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // uint64 size = 2;
  void clear_size();
  uint64_t size() const;
  void set_size(uint64_t value);
  private:
  uint64_t _internal_size() const;
  void _internal_set_size(uint64_t value);
  public:

  // uint64 begin_idx = 3;
  void clear_begin_idx();
  uint64_t begin_idx() const;
  void set_begin_idx(uint64_t value);
  private:
  uint64_t _internal_begin_idx() const;
  void _internal_set_begin_idx(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:proto.FileMeta)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr usr_path_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr local_path_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr hash_;
    uint64_t id_;
    uint64_t size_;
    uint64_t begin_idx_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_file_2eproto;
};
// -------------------------------------------------------------------

class FileMetaResume final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:proto.FileMetaResume) */ {
 public:
  inline FileMetaResume() : FileMetaResume(nullptr) {}
  ~FileMetaResume() override;
  explicit PROTOBUF_CONSTEXPR FileMetaResume(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FileMetaResume(const FileMetaResume& from);
  FileMetaResume(FileMetaResume&& from) noexcept
    : FileMetaResume() {
    *this = ::std::move(from);
  }

  inline FileMetaResume& operator=(const FileMetaResume& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileMetaResume& operator=(FileMetaResume&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileMetaResume& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileMetaResume* internal_default_instance() {
    return reinterpret_cast<const FileMetaResume*>(
               &_FileMetaResume_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(FileMetaResume& a, FileMetaResume& b) {
    a.Swap(&b);
  }
  inline void Swap(FileMetaResume* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileMetaResume* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileMetaResume* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FileMetaResume>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FileMetaResume& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FileMetaResume& from) {
    FileMetaResume::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileMetaResume* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "proto.FileMetaResume";
  }
  protected:
  explicit FileMetaResume(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUsrPathFieldNumber = 1,
    kLocalPathFieldNumber = 2,
    kBeginIdxFieldNumber = 3,
    kFileSizeFieldNumber = 4,
    kIsUploadFieldNumber = 5,
  };
  // string usr_path = 1;
  void clear_usr_path();
  const std::string& usr_path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_usr_path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_usr_path();
  PROTOBUF_NODISCARD std::string* release_usr_path();
  void set_allocated_usr_path(std::string* usr_path);
  private:
  const std::string& _internal_usr_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_usr_path(const std::string& value);
  std::string* _internal_mutable_usr_path();
  public:

  // string local_path = 2;
  void clear_local_path();
  const std::string& local_path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_local_path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_local_path();
  PROTOBUF_NODISCARD std::string* release_local_path();
  void set_allocated_local_path(std::string* local_path);
  private:
  const std::string& _internal_local_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_local_path(const std::string& value);
  std::string* _internal_mutable_local_path();
  public:

  // uint64 begin_idx = 3;
  void clear_begin_idx();
  uint64_t begin_idx() const;
  void set_begin_idx(uint64_t value);
  private:
  uint64_t _internal_begin_idx() const;
  void _internal_set_begin_idx(uint64_t value);
  public:

  // uint64 file_size = 4;
  void clear_file_size();
  uint64_t file_size() const;
  void set_file_size(uint64_t value);
  private:
  uint64_t _internal_file_size() const;
  void _internal_set_file_size(uint64_t value);
  public:

  // bool is_upload = 5;
  void clear_is_upload();
  bool is_upload() const;
  void set_is_upload(bool value);
  private:
  bool _internal_is_upload() const;
  void _internal_set_is_upload(bool value);
  public:

  // @@protoc_insertion_point(class_scope:proto.FileMetaResume)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr usr_path_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr local_path_;
    uint64_t begin_idx_;
    uint64_t file_size_;
    bool is_upload_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_file_2eproto;
};
// -------------------------------------------------------------------

class FileTrunk final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:proto.FileTrunk) */ {
 public:
  inline FileTrunk() : FileTrunk(nullptr) {}
  ~FileTrunk() override;
  explicit PROTOBUF_CONSTEXPR FileTrunk(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FileTrunk(const FileTrunk& from);
  FileTrunk(FileTrunk&& from) noexcept
    : FileTrunk() {
    *this = ::std::move(from);
  }

  inline FileTrunk& operator=(const FileTrunk& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileTrunk& operator=(FileTrunk&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileTrunk& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileTrunk* internal_default_instance() {
    return reinterpret_cast<const FileTrunk*>(
               &_FileTrunk_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(FileTrunk& a, FileTrunk& b) {
    a.Swap(&b);
  }
  inline void Swap(FileTrunk* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileTrunk* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileTrunk* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FileTrunk>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FileTrunk& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FileTrunk& from) {
    FileTrunk::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileTrunk* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "proto.FileTrunk";
  }
  protected:
  explicit FileTrunk(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 3,
    kIdFieldNumber = 1,
    kIdxFieldNumber = 2,
  };
  // bytes data = 3;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // uint64 id = 1;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // uint64 idx = 2;
  void clear_idx();
  uint64_t idx() const;
  void set_idx(uint64_t value);
  private:
  uint64_t _internal_idx() const;
  void _internal_set_idx(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:proto.FileTrunk)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
    uint64_t id_;
    uint64_t idx_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_file_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FileMeta

// uint64 id = 1;
inline void FileMeta::clear_id() {
  _impl_.id_ = uint64_t{0u};
}
inline uint64_t FileMeta::_internal_id() const {
  return _impl_.id_;
}
inline uint64_t FileMeta::id() const {
  // @@protoc_insertion_point(field_get:proto.FileMeta.id)
  return _internal_id();
}
inline void FileMeta::_internal_set_id(uint64_t value) {
  
  _impl_.id_ = value;
}
inline void FileMeta::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:proto.FileMeta.id)
}

// uint64 size = 2;
inline void FileMeta::clear_size() {
  _impl_.size_ = uint64_t{0u};
}
inline uint64_t FileMeta::_internal_size() const {
  return _impl_.size_;
}
inline uint64_t FileMeta::size() const {
  // @@protoc_insertion_point(field_get:proto.FileMeta.size)
  return _internal_size();
}
inline void FileMeta::_internal_set_size(uint64_t value) {
  
  _impl_.size_ = value;
}
inline void FileMeta::set_size(uint64_t value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:proto.FileMeta.size)
}

// uint64 begin_idx = 3;
inline void FileMeta::clear_begin_idx() {
  _impl_.begin_idx_ = uint64_t{0u};
}
inline uint64_t FileMeta::_internal_begin_idx() const {
  return _impl_.begin_idx_;
}
inline uint64_t FileMeta::begin_idx() const {
  // @@protoc_insertion_point(field_get:proto.FileMeta.begin_idx)
  return _internal_begin_idx();
}
inline void FileMeta::_internal_set_begin_idx(uint64_t value) {
  
  _impl_.begin_idx_ = value;
}
inline void FileMeta::set_begin_idx(uint64_t value) {
  _internal_set_begin_idx(value);
  // @@protoc_insertion_point(field_set:proto.FileMeta.begin_idx)
}

// string usr_path = 4;
inline void FileMeta::clear_usr_path() {
  _impl_.usr_path_.ClearToEmpty();
}
inline const std::string& FileMeta::usr_path() const {
  // @@protoc_insertion_point(field_get:proto.FileMeta.usr_path)
  return _internal_usr_path();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileMeta::set_usr_path(ArgT0&& arg0, ArgT... args) {
 
 _impl_.usr_path_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:proto.FileMeta.usr_path)
}
inline std::string* FileMeta::mutable_usr_path() {
  std::string* _s = _internal_mutable_usr_path();
  // @@protoc_insertion_point(field_mutable:proto.FileMeta.usr_path)
  return _s;
}
inline const std::string& FileMeta::_internal_usr_path() const {
  return _impl_.usr_path_.Get();
}
inline void FileMeta::_internal_set_usr_path(const std::string& value) {
  
  _impl_.usr_path_.Set(value, GetArenaForAllocation());
}
inline std::string* FileMeta::_internal_mutable_usr_path() {
  
  return _impl_.usr_path_.Mutable(GetArenaForAllocation());
}
inline std::string* FileMeta::release_usr_path() {
  // @@protoc_insertion_point(field_release:proto.FileMeta.usr_path)
  return _impl_.usr_path_.Release();
}
inline void FileMeta::set_allocated_usr_path(std::string* usr_path) {
  if (usr_path != nullptr) {
    
  } else {
    
  }
  _impl_.usr_path_.SetAllocated(usr_path, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.usr_path_.IsDefault()) {
    _impl_.usr_path_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:proto.FileMeta.usr_path)
}

// string local_path = 5;
inline void FileMeta::clear_local_path() {
  _impl_.local_path_.ClearToEmpty();
}
inline const std::string& FileMeta::local_path() const {
  // @@protoc_insertion_point(field_get:proto.FileMeta.local_path)
  return _internal_local_path();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileMeta::set_local_path(ArgT0&& arg0, ArgT... args) {
 
 _impl_.local_path_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:proto.FileMeta.local_path)
}
inline std::string* FileMeta::mutable_local_path() {
  std::string* _s = _internal_mutable_local_path();
  // @@protoc_insertion_point(field_mutable:proto.FileMeta.local_path)
  return _s;
}
inline const std::string& FileMeta::_internal_local_path() const {
  return _impl_.local_path_.Get();
}
inline void FileMeta::_internal_set_local_path(const std::string& value) {
  
  _impl_.local_path_.Set(value, GetArenaForAllocation());
}
inline std::string* FileMeta::_internal_mutable_local_path() {
  
  return _impl_.local_path_.Mutable(GetArenaForAllocation());
}
inline std::string* FileMeta::release_local_path() {
  // @@protoc_insertion_point(field_release:proto.FileMeta.local_path)
  return _impl_.local_path_.Release();
}
inline void FileMeta::set_allocated_local_path(std::string* local_path) {
  if (local_path != nullptr) {
    
  } else {
    
  }
  _impl_.local_path_.SetAllocated(local_path, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.local_path_.IsDefault()) {
    _impl_.local_path_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:proto.FileMeta.local_path)
}

// string hash = 6;
inline void FileMeta::clear_hash() {
  _impl_.hash_.ClearToEmpty();
}
inline const std::string& FileMeta::hash() const {
  // @@protoc_insertion_point(field_get:proto.FileMeta.hash)
  return _internal_hash();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileMeta::set_hash(ArgT0&& arg0, ArgT... args) {
 
 _impl_.hash_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:proto.FileMeta.hash)
}
inline std::string* FileMeta::mutable_hash() {
  std::string* _s = _internal_mutable_hash();
  // @@protoc_insertion_point(field_mutable:proto.FileMeta.hash)
  return _s;
}
inline const std::string& FileMeta::_internal_hash() const {
  return _impl_.hash_.Get();
}
inline void FileMeta::_internal_set_hash(const std::string& value) {
  
  _impl_.hash_.Set(value, GetArenaForAllocation());
}
inline std::string* FileMeta::_internal_mutable_hash() {
  
  return _impl_.hash_.Mutable(GetArenaForAllocation());
}
inline std::string* FileMeta::release_hash() {
  // @@protoc_insertion_point(field_release:proto.FileMeta.hash)
  return _impl_.hash_.Release();
}
inline void FileMeta::set_allocated_hash(std::string* hash) {
  if (hash != nullptr) {
    
  } else {
    
  }
  _impl_.hash_.SetAllocated(hash, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.hash_.IsDefault()) {
    _impl_.hash_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:proto.FileMeta.hash)
}

// -------------------------------------------------------------------

// FileMetaResume

// string usr_path = 1;
inline void FileMetaResume::clear_usr_path() {
  _impl_.usr_path_.ClearToEmpty();
}
inline const std::string& FileMetaResume::usr_path() const {
  // @@protoc_insertion_point(field_get:proto.FileMetaResume.usr_path)
  return _internal_usr_path();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileMetaResume::set_usr_path(ArgT0&& arg0, ArgT... args) {
 
 _impl_.usr_path_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:proto.FileMetaResume.usr_path)
}
inline std::string* FileMetaResume::mutable_usr_path() {
  std::string* _s = _internal_mutable_usr_path();
  // @@protoc_insertion_point(field_mutable:proto.FileMetaResume.usr_path)
  return _s;
}
inline const std::string& FileMetaResume::_internal_usr_path() const {
  return _impl_.usr_path_.Get();
}
inline void FileMetaResume::_internal_set_usr_path(const std::string& value) {
  
  _impl_.usr_path_.Set(value, GetArenaForAllocation());
}
inline std::string* FileMetaResume::_internal_mutable_usr_path() {
  
  return _impl_.usr_path_.Mutable(GetArenaForAllocation());
}
inline std::string* FileMetaResume::release_usr_path() {
  // @@protoc_insertion_point(field_release:proto.FileMetaResume.usr_path)
  return _impl_.usr_path_.Release();
}
inline void FileMetaResume::set_allocated_usr_path(std::string* usr_path) {
  if (usr_path != nullptr) {
    
  } else {
    
  }
  _impl_.usr_path_.SetAllocated(usr_path, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.usr_path_.IsDefault()) {
    _impl_.usr_path_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:proto.FileMetaResume.usr_path)
}

// string local_path = 2;
inline void FileMetaResume::clear_local_path() {
  _impl_.local_path_.ClearToEmpty();
}
inline const std::string& FileMetaResume::local_path() const {
  // @@protoc_insertion_point(field_get:proto.FileMetaResume.local_path)
  return _internal_local_path();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileMetaResume::set_local_path(ArgT0&& arg0, ArgT... args) {
 
 _impl_.local_path_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:proto.FileMetaResume.local_path)
}
inline std::string* FileMetaResume::mutable_local_path() {
  std::string* _s = _internal_mutable_local_path();
  // @@protoc_insertion_point(field_mutable:proto.FileMetaResume.local_path)
  return _s;
}
inline const std::string& FileMetaResume::_internal_local_path() const {
  return _impl_.local_path_.Get();
}
inline void FileMetaResume::_internal_set_local_path(const std::string& value) {
  
  _impl_.local_path_.Set(value, GetArenaForAllocation());
}
inline std::string* FileMetaResume::_internal_mutable_local_path() {
  
  return _impl_.local_path_.Mutable(GetArenaForAllocation());
}
inline std::string* FileMetaResume::release_local_path() {
  // @@protoc_insertion_point(field_release:proto.FileMetaResume.local_path)
  return _impl_.local_path_.Release();
}
inline void FileMetaResume::set_allocated_local_path(std::string* local_path) {
  if (local_path != nullptr) {
    
  } else {
    
  }
  _impl_.local_path_.SetAllocated(local_path, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.local_path_.IsDefault()) {
    _impl_.local_path_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:proto.FileMetaResume.local_path)
}

// uint64 begin_idx = 3;
inline void FileMetaResume::clear_begin_idx() {
  _impl_.begin_idx_ = uint64_t{0u};
}
inline uint64_t FileMetaResume::_internal_begin_idx() const {
  return _impl_.begin_idx_;
}
inline uint64_t FileMetaResume::begin_idx() const {
  // @@protoc_insertion_point(field_get:proto.FileMetaResume.begin_idx)
  return _internal_begin_idx();
}
inline void FileMetaResume::_internal_set_begin_idx(uint64_t value) {
  
  _impl_.begin_idx_ = value;
}
inline void FileMetaResume::set_begin_idx(uint64_t value) {
  _internal_set_begin_idx(value);
  // @@protoc_insertion_point(field_set:proto.FileMetaResume.begin_idx)
}

// uint64 file_size = 4;
inline void FileMetaResume::clear_file_size() {
  _impl_.file_size_ = uint64_t{0u};
}
inline uint64_t FileMetaResume::_internal_file_size() const {
  return _impl_.file_size_;
}
inline uint64_t FileMetaResume::file_size() const {
  // @@protoc_insertion_point(field_get:proto.FileMetaResume.file_size)
  return _internal_file_size();
}
inline void FileMetaResume::_internal_set_file_size(uint64_t value) {
  
  _impl_.file_size_ = value;
}
inline void FileMetaResume::set_file_size(uint64_t value) {
  _internal_set_file_size(value);
  // @@protoc_insertion_point(field_set:proto.FileMetaResume.file_size)
}

// bool is_upload = 5;
inline void FileMetaResume::clear_is_upload() {
  _impl_.is_upload_ = false;
}
inline bool FileMetaResume::_internal_is_upload() const {
  return _impl_.is_upload_;
}
inline bool FileMetaResume::is_upload() const {
  // @@protoc_insertion_point(field_get:proto.FileMetaResume.is_upload)
  return _internal_is_upload();
}
inline void FileMetaResume::_internal_set_is_upload(bool value) {
  
  _impl_.is_upload_ = value;
}
inline void FileMetaResume::set_is_upload(bool value) {
  _internal_set_is_upload(value);
  // @@protoc_insertion_point(field_set:proto.FileMetaResume.is_upload)
}

// -------------------------------------------------------------------

// FileTrunk

// uint64 id = 1;
inline void FileTrunk::clear_id() {
  _impl_.id_ = uint64_t{0u};
}
inline uint64_t FileTrunk::_internal_id() const {
  return _impl_.id_;
}
inline uint64_t FileTrunk::id() const {
  // @@protoc_insertion_point(field_get:proto.FileTrunk.id)
  return _internal_id();
}
inline void FileTrunk::_internal_set_id(uint64_t value) {
  
  _impl_.id_ = value;
}
inline void FileTrunk::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:proto.FileTrunk.id)
}

// uint64 idx = 2;
inline void FileTrunk::clear_idx() {
  _impl_.idx_ = uint64_t{0u};
}
inline uint64_t FileTrunk::_internal_idx() const {
  return _impl_.idx_;
}
inline uint64_t FileTrunk::idx() const {
  // @@protoc_insertion_point(field_get:proto.FileTrunk.idx)
  return _internal_idx();
}
inline void FileTrunk::_internal_set_idx(uint64_t value) {
  
  _impl_.idx_ = value;
}
inline void FileTrunk::set_idx(uint64_t value) {
  _internal_set_idx(value);
  // @@protoc_insertion_point(field_set:proto.FileTrunk.idx)
}

// bytes data = 3;
inline void FileTrunk::clear_data() {
  _impl_.data_.ClearToEmpty();
}
inline const std::string& FileTrunk::data() const {
  // @@protoc_insertion_point(field_get:proto.FileTrunk.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileTrunk::set_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:proto.FileTrunk.data)
}
inline std::string* FileTrunk::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:proto.FileTrunk.data)
  return _s;
}
inline const std::string& FileTrunk::_internal_data() const {
  return _impl_.data_.Get();
}
inline void FileTrunk::_internal_set_data(const std::string& value) {
  
  _impl_.data_.Set(value, GetArenaForAllocation());
}
inline std::string* FileTrunk::_internal_mutable_data() {
  
  return _impl_.data_.Mutable(GetArenaForAllocation());
}
inline std::string* FileTrunk::release_data() {
  // @@protoc_insertion_point(field_release:proto.FileTrunk.data)
  return _impl_.data_.Release();
}
inline void FileTrunk::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  _impl_.data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:proto.FileTrunk.data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_file_2eproto
